### ISSUE TITLE
HOW TO RUN THIS THING 🌲

### ISSUE THREAD

**Issue by ktb683** [ClojureTO/kata#21]
<img width="654" alt="screen shot 2015-12-02 at 8 20 03 pm" src="https://cloud.githubusercontent.com/assets/3971300/11549237/55a9e112-9932-11e5-8c67-d8ec19669c8b.png">

Please update docs on how to open the server. kthxbye

**Comment by yogthos** [comment]
added some docs in the README.md, hopefully it all makes sense :)
